"""Feature-wise Linear Modulation (FiLM) for speed conditioning.

Maps a scalar conditioning signal (walking speed v) to channel-wise scale (gamma)
and shift (beta) parameters applied to intermediate representations:
    FiLM(h, v) = (1 + gamma(v)) * h + beta(v)
where gamma and beta are generated by a 2-layer MLP.
"""

import torch
import torch.nn as nn


class FiLM(nn.Module):
    """2-layer MLP generating FiLM modulation parameters (gamma, beta) for a hidden state."""
    
    def __init__(self, cond_dim: int = 1, d_model: int = 64, hidden_dim: int = 32):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(cond_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, 2 * d_model),
        )
        
        # Initialize final layer weights and biases to zero so FiLM starts as identity:
        # gamma = 0, beta = 0 -> (1 + 0) * h + 0 = h
        nn.init.zeros_(self.mlp[-1].weight)
        nn.init.zeros_(self.mlp[-1].bias)

    def forward(self, h: torch.Tensor, cond: torch.Tensor) -> torch.Tensor:
        """Apply FiLM modulation.
        
        Args:
            h: Hidden state tensor of shape (batch_size, seq_len, d_model)
            cond: Conditioning tensor of shape (batch_size, cond_dim) or (batch_size, 1)
            
        Returns:
            Modulated hidden state of shape (batch_size, seq_len, d_model)
        """
        # Shape: (batch_size, 2 * d_model)
        params = self.mlp(cond)
        gamma, beta = torch.chunk(params, 2, dim=-1)
        
        # Broadcast across time dimension: (batch_size, 1, d_model)
        gamma = gamma.unsqueeze(1)
        beta = beta.unsqueeze(1)
        
        return (1.0 + gamma) * h + beta
